name: Base Image Build and Deploy

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:
    environment: >
      ${{
        github.ref_name == 'main' && 'prod' || 'prod'
      }}

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      SERVER_ECR_REGISTRY: ${{ vars.SERVER_ECR_REGISTRY }}
      MIGRATIONS_ECR_REGISTRY: ${{ vars.MIGRATIONS_ECR_REGISTRY }}
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push server image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        target: prod
        push: true
        tags: ${{ env.SERVER_ECR_REGISTRY }}:latest
        cache-from: type=gha,key=base-server
        cache-to: type=gha,mode=max,key=base-server
    
    - name: Build and push migrations image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        target: migration
        push: true
        tags: ${{ env.MIGRATIONS_ECR_REGISTRY }}:latest
        cache-from: type=gha,key=base-migrations
        cache-to: type=gha,mode=max,key=base-migrations